# Figure out the technical details from the so-called "category" of
# this WordPress instance

# A "managed" WordPress instance is one over which the VPSI staff
# exerts IT control (re permissions, software updates).
_category_managed_groups:
  - prod-subdomains
  - prod-inside
  - prod-labs
  - prod-sandbox

# TODO: This is about to change (@jdelasoie) when we fetch the
# inventory from wp-veritas
wp_is_managed: "{{ group_names |                                             \
                   intersect(_category_managed_groups) | cast_to_boolean }}"
