- name: "PersistentVolumeClaim/wordpress-0"
  openshift:
    state: latest
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: wordpress-0
      namespace: "{{ ansible_oc_namespace }}"
    spec:
      accessModes:
      - ReadWriteMany
      volumeName: wordpress-volume
    