---
# Infrastructure deployment tasks
#
- name: pv
  import_tasks: "mnsft-persistent-volume.yml"
  tags:
    - blue

- name: pvc
  import_tasks: "mnsft-persistent-claim.yml"
  tags:
    - blue

- name: OpenProject deployment
  import_tasks: "mnsft-deploy-wp.yml"
  tags:
    - blue

- name: OpenProject service
  import_tasks: "mnsft-serve-wp.yml"
  tags:
    - blue
- name: OpenProject route
  import_tasks: "mnsft-route-wp.yml"
  tags:
    - blue

#