---


- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{name}}"
      name: "{{name}}"
      namespace: "myproject"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: "{{name}}"
        spec:
          containers:
            - name: "{{name}}"
              volumeMounts:
                - mountPath: /var/www/html
                  name: "nfsvol-{{name}}"
          volumes:
            - name: "nfsvol-{{name}}"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-{{name}}'
      triggers:
        - type: ConfigChange

        - type: ImageChange
          imageChangeParams:
            containerNames:
            - "{{ name }}"
            from:
              kind: ImageStreamTag
              name: "httpd:prod"
              namespace: "myproject"
             
  tags: dc
