---



- name: "Service"
  connection: local
  openshift:
    state: latest
    kind: Service
    name: "{{name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
        name: "{{name}}"
        labels:
          run: "{{name}}"
        namespace: myproject
    spec:
        selector:
            run: "{{name}}"
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
  tags: svc
