wp_nginx_ci_flavors:
  - name: apple
    fruit: 'ğŸ'
  - name: grapes
    fruit: 'ğŸ‡'
  - name: kiwi
    fruit: 'ğŸ¥'
  - name: lemon
    fruit: 'ğŸ‹'
  - name: orange
    fruit: 'ğŸŠ'
  - name: alpha
  - name: rc
