static_routes: 
  wwp:
    - name: httpd-www
      hostname: www.epfl.ch    
    - name: httpd-inside
      hostname: inside.epfl.ch
    - name: httpd-formation-wp
      hostname: formation-wp.epfl.ch
    # www-2018 has 'httpd-sandbox' service and not 'varnish-varnish'
    # - name: httpd-www2018
    #   hostname: www2018.epfl.ch 

  wwp-test:
    - name: httpd-int
      hostname: migration-wp.epfl.ch 
    - name: httpd-charte-wp
      hostname: charte-wp.epfl.ch
    
      # cloudflare test
    - name: httpd-wp-cloudflare-origin
      hostname: wp-cloudflare-origin.epfl.ch
    - name: httpd-wp-cloudflare
      hostname: wp-cloudflare.epfl.ch

    - name: httpd-cburki
      hostname: env-cb-os-exopge.epfl.ch
    - name: httpd-lvenries
      hostname: env-lv-os-exopge.epfl.ch
    - name: httpd-gcharmier
      hostname: env-gc-os-exopge.epfl.ch
    - name: httpd-lchaboudez
      hostname: env-lc-os-exopge.epfl.ch
    - name: httpd-dev
      hostname: wp5-os-exopge.epfl.ch
    - name: httpd-dev-1
      hostname: wp1-os-exopge.epfl.ch
    - name: httpd-dev-2
      hostname: wp2-os-exopge.epfl.ch
    - name: httpd-dev-3
      hostname: wp3-os-exopge.epfl.ch
    - name: httpd-dev-4
      hostname: wp4-os-exopge.epfl.ch
