---



- name: "Route"
  connection: local
  openshift:
    state: latest
    kind: Route
    name: "{{name}}"
    namespace: "{{ openshift_namespace }}"
    apiVersion: v1
    metadata:
        name: "{{name}}"
    spec:
        host: "{{name}}-{{openshift_namespace}}.128.178.222.83.nip.io"
        port:
            targetPort: 8080
        to:
            kind: Service
            name: "{{name}}"
        tls:
            insecureEdgeTerminationPolicy: Redirect
            termination: edge
  tags: rt
