#TODO change secret name
- name: "Image Stream secret creation"
  shell:
     cmd: |
        oc delete secret docker-registry {{ secret_name }}
        oc create secret docker-registry {{ secret_name }} --docker-server={{ epfl_openshift_registry_address }} --docker-username={{ epfl_openshift_credentials.user }} --docker-password={{ epfl_openshift_credentials.token }}
 
- name: "Secret link check"
  shell:
        cmd: |
          set -e -x
          oc get serviceaccount default -o yaml
  register: svc_acc
  
- set_fact:
    contains_secret_link: "{{ svc_acc.stdout | from_yaml | contains_c2c_secret_link( lookup('vars', 'secret_name') ) }}"

- name: "Linking Secret"
  shell:
     cmd: |
       set -e -x
       oc --namespace {{minishift_namespace}} secrets link wp-int {{ secret_name }} --for=pull
  when:  not contains_secret_link

- debug: msg="Secret created and linked successfully"
  