---



- name: "Route"
  connection: local
  openshift:
    state: latest
    kind: Route
    name: "mgmt"
    namespace: "myproject"
    apiVersion: v1
    metadata:
        name: "mgmt"
    spec:
        host: "mgmt-myproject.192.168.99.100.nip.io"
        port:
            targetPort: 80
        to:
            kind: Service
            name: "mgmt"
  tags: rt
