---



- name: "Service"
  connection: local
  openshift:
    state: latest
    kind: Service
    name: "mgmt"
    namespace: "{{ minishift_namespace }}"
    apiVersion: v1
    metadata:
        name: "mgmt"
        labels:
          run: "mgmt"
        namespace: myproject
    spec:
        selector:
            run: "mgmt"
        ports:
        - port: 80
          protocol: TCP
          targetPort: 80
  tags: svc
