---
- name: "PersistentVolume"
  connection: local
  openshift:
    state: latest
    as_user: "system:admin"
    kind: PersistentVolume
    name: "nfs-pv-mgmt"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pv-mgmt'
      labels:
          id: "mgmt"
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: '/wp'
        server: 128.179.146.8
        readOnly: false
  tags: pv
