---



- name: "PersistentVolumeClaim"
  connection: local
  openshift:
    state: latest
    kind: PersistentVolumeClaim
    name: "nfs-pvc-mgmt"
    namespace: "{{minishift_namespace}}"
    apiVersion: v1
    metadata:
      name: 'nfs-pvc-mgmt'
      annotations:
        volume.beta.kubernetes.io/storage-class: wwp-int-wordpress-sites
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 1Gi

  tags: pvc