---



- name: "Route"
  openshift:
    state: latest
    kind: Route
    name: "{{name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
        name: "{{name}}"
    spec:
        host: "{{name}}-myproject.192.168.99.100.nip.io"
        port:
            targetPort: 80
        to:
            kind: Service
            name: "{{name}}"
  tags: rt
