# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-namespace/vars/opdo-secrets-test.yml
#
# ðŸ’¡ This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_test/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_test.pem"

opdo:
  urls:
    - https://itsaudit0026.xaas.epfl.ch:9200/opdo-test/_doc
    - https://itsaudit0025.xaas.epfl.ch:9200/opdo-test/_doc
  api_key:
    username: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAh3K/5SbUex7pHD9xt9z7rXv0jEmw+AExZCXRh3Veg9ZJECUSpU9YSV47LqvD03ayvHQEWyAxPpQ8VL2NMR1xsuHUboLvMXOJ1c8y+NyKsihHIdLxweJVy7bA1OU3/9xB+gEFEiC/09CcYHG7PB6zxfNykwCgDQ8YwA5zgRrSQderMLJtpKtL+4HlE2PkxxRgz8Tuh/zFaqPef+skFIVNiyG4gVo+jBxTb22EGyjhM+pAtvELq8geo0Fvas9tkB/N9/lIIwNUn3CsAllHgZ+Ii0QWoyhPOzTEVG7IWqWqntodAgA+SObCaLbrsmpsn89kEC3lABnxsK19ECWRIVceczBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBHKElnHZEUrmgUDqHnA+MDgCAhsnUT+Uv+9JZS60c62MauDHSf0If59xYRATku8RS0wA==]
    password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAULyirotv22MD0JejfozXc3zGQ11mQ0YkqSIHXQdNTxvx1QGpCWqChUx1zBWaVaAwGk6gFD9FlIe2rsGwwj1asceostJUM1K4NzoHqjvpHTI9puoxxnGBcFKqVvnU0srpuj/g1eKpD1LsU2gexQx2+in6d0Fs2kuIvteB8PAOzI43/UKHym1MiPfnMWkzW8jTsmmCuRevjOgEZyZVxyfi6/QY9WJ2l0chd2W4wto9R9ajQw3OIzaZr6uj4MRCIs/PGLi/0Mr64TPjlEZodbAqiDiQrq3ZGCQi/agCasfiao/7Bsu05W4Z/IkhIn7Ch5WvcO0ugW09nZtqJC8SMJnR3TBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBHs9AWOpwCZjTzbNVYZsOxgCD6Jssljcb8bDFgBXovHrSQGwKfgKXkp8xFssLUi4JO8Q==]

certificate: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_wp_test/OPDo_test/OPDo_ca_test.crt') }}"

