# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-namespace/vars/serving-secrets-test.yml
#
# ðŸ’¡ This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_prod/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_prod.pem"

s3_backup_credentials:
  bucket_name: svc0041-f09a145f151acfe768583301e0389e65
  keyId: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAvWKll4PlGohB57wT1htqfssW2OCh8AcQo1pBl/y71PGXqeFQoRhKTcLvyZC4dsLpmky+G6J6iZ1dQw7cv+kTFqyKVVnNwQJdJF8aDapXOSDOmm/0CkZeInAp+vqGazxv81iYA0i6ECvWDT9TzR/YK1Nfft+tzECTqAD7IeMf0e4gJYxcHdqmltGzOWnD4NiBepPp57uMMjWlU5hKpXcV36nVfSRujfStZlbxpvAvuVtJ91CijS1EufMerSzr/QOzET3FZXP0C2e5nAveFn3TCNHXHCln2/odjBzEVY/I0J4cb6kVv4zgMazQ7syFMhKLmYMkxsO6wkfYB5uB+fuuwDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB/9jzjL2fXmIisrenxx2HSgCC8A3FwR+tbloNSBJY+ugEt2arlsRzb7RpyqWWNUyJtKA==]
  accessSecret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAj1JpGNIqOVNNb9QUx7o3pCf978Bx7uMPiG0WTWVkeO1kGBIVT6QakoJVSxOTNAyydeh/99Tt56A9X1bihMy4J8QuNloOmzOooiWpRliq3pSBop2qqObvjSVTiOpCf2e/yC/t5E0CUj4nsXgdcu18mAW3UmI42D28nq6CzZTz+7bwMF1y54ES/bDEQtPQmnNlM+ii7HEpc5E4/h8Ed/9c79RToZmqTqdSMyoKUa3+w8SSxVTW0yDzvfCziOnphevLcu+wvuUbt8wnnYIMsr16goSPpmdw8Lxxm860wS51DDwLpKVQDR7PCW+NmKD0T9bp4SyFlDN/sA5zN1TaOs9gpjBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDq8yAorVUDqjdQA5OM6cvagDB5iV5tVVb6Fq9J1G3uPwwaAIQyIa7EqIDf9d9wUrNJaWlgFnOYgWurRRaLyc/ysAY=]

s3_ro_prod_credentials:
  bucket_name: svc0041-f09a145f151acfe768583301e0389e65
  keyId: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAZT03lxK6A6NUjm34ywTbk5JhPx8+haUcT89vdaz09DhGzJg0OoSi2y6u0zS0GBpjRK8c3q1lcP/MLVud1GB2C2xXaiCQNl1xScAzHnw7U8Nsi/9nCIhVZTvmmYeZR7fsGgxp8UcZH91cyaCkDgBPsJsv3f7aCuQUtIR2/YWs/DnypVLMNSKRNzDI+BAaTaGSQvSRXg1V62xC08bXBpTBL0XgoyVkf8sEg/jnRWPhuM+tWRWPw2t3gRhV9pdPQWEWwJe5BJq4Fzo4GWJrqGpAYMijn5K9zvQtS/KdI71CGYzpnOFnL6LvQKBiaoF/Mljbo/xvaI2ONabYZDKn4iqkGTBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB8+/7peTvJwBcdEuQwhNo3gCBZRcZwjhBU/kbNc1tHUTFjYKFrQ4kjvDvbGHrbKlM2Ww==]
  accessSecret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAdJ3ayDS4RCZgiwUVIezd2gK+4LUINEO6goe+ze2PxDL8rzxCKan8kCphYjsn+qzok+VcalOqqn1s6nj9RsgGULss24AEyxYACoxDUgv7ken/8kVGdBgkDzPrNg29J+JhIioISozvkT/DkF2IJK9657klPfCRJwRkKjaDaq6XtyAnvxK3dtyZ7mLu/3hg4P6UuoeC4hcEZFGtODvnLLd4ZXlEjuCnD/Y3pGHNMez/9/PJNuOs9CPMaIIk2aTMYpcPIoaVxi4v0p7iqCdQrbgn3LZ6HoeonwyzKbWu8poXM2TKl3yaX8/WsVi16BF0GAAijaj0RtFSOMvlxMTy2+eIfTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBACRHi+AWChha6WCOau/DRTgDDvzKu6GsXkaroykBUm4Jmj792OzqbJbvsJQOHUh+TewtMFK+GV9aSeJwG+wWuC4tI=]
